### ISSUE TITLE
È possibile non lanciare il browser

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/dballe-web#13]
C'è una maniera per non far partire automaticamente il web-browser al lancio di dballe-web?

Sarebbe utile ad es. per sessioni remote (santo lavoro agile!) in cui è più conveniente ridirezionare la porta allocata da dballe-web con una roba tipo `ssh -L 44547:localhost:44547 user@host` ed aprire la sessione in un browser locale.

**Comment by pat1** [comment]
Avevo chiesto questa cosa esplicitamente tempo fa, ma è stata appositamente vietata.
Le motivazioni non sono in grado di riportarle correttamente e lo lascio fare ai miei colleghi.

**Comment by spanezz** [comment]
Dunque, il problema è che la porta in cui ascolta dballe-web non deve essere accessibile ad altri utenti, sia all'interno che all'esterno della macchina.

Anche il port forwarding tradizionale è quindi un problema, perché se ascolto su localhost:5000, gli altri utenti all'interno della macchina possono connettercisi.

Ho trovato però un'altra possibilità potenzialmente esplorabile: https://serverfault.com/questions/127794/forward-local-port-or-socket-file-to-remote-socket-file

Questo risolverebbe il problema di non rendere la porta accessibile sulla macchina remota, ma rimane il problema di avere al porta accessibile sulla macchina locale. Quel problema al momento c'è comunque, ma se dballe-web viene solitamente usato su workstation personali, è un problema minore.

Risolvere il problema nello stesso modo anche sulla macchina dove gira il browser, al momento non sembra possibile:

* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1614216
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=451721

**Comment by spanezz** [comment]
Lato client si può probabilmente mitigare qualcosa usando `unshare(1)` per lanciare sia il tunnel ssh che il browser senza che la porta che usano per comunicare sia visibile agli altri processi del sistema, ma è una cosa che conosco solo in teoria e in pratica non ho mai provato.

Correzione: ho fatto qualche prova ora, e sembra aver bisogno di root.

Altre possibilità sono tracciate qui: https://www.enricozini.org/blog/2021/debian/run-a-webserver-for-a-specific-user-only/

**Comment by spanezz** [comment]
Implementato nel branch `flask`, ancora non mergiato in master.

Su consiglio di @edigiacomo ho anche implementato un token da usare nell'URL per collegarsi da browser, che dovrebbe evitare l'accesso da parte di altri utenti locali.

Un passo successivo sarebbe usare unix domain socket se si sta girando con l'intenzione di essere forwardati via ssh, che eviterebbe del tutto l'allocazione di una porta sulla macchina remota, come sicurezza, col token di accesso, ormai ci siamo, e lo lascierei per un altro ticket.

**Comment by spanezz** [comment]
Ho fatto merge in master del lavoro di riorganizzazione.

Ora lanciando dballe-web compare un'interfaccia testuale che mostra l'URL da usare, che apre un browser se si digita `w`, e mostra anche il comando per il tunneling ssh e l'URL da usare per accedere via tunnel.
