### ISSUE TITLE
test failing in CentOS8

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/dballe-web#15]
e.g.:
https://simc.arpae.it/moncic-ci/dballe-web/202109010820/master/centos8/build.log

https://simc.arpae.it/moncic-ci/dballe-web/202109010820/master/fedora34/build.log

**Comment by spanezz** [comment]
Dopo aver introdotto l'autenticazione a token, mancava l'usarla nei test. L'ho implementato in 7a8e4f4c9a9f20dc969e1313f546b9caa5119f5f

Fallisce ancora centos8 perché ha una versione di Flask troppo vecchia (ha la `1:0.12.2-4.el8` mentre su centos7 arriva già la `0:1.1.2-4.el7`)

**Comment by spanezz** [comment]
Si può avere una versione di flask piú nuova su centos8? (O almeno la stessa di centos7, anche se non avrei mai creduto di trovarmi a scrivere "avere almeno la stessa versione di centos7")

**Comment by brancomat** [comment]
> Si può avere una versione di flask piú nuova su centos8?

Al momento flask su centos7 è distribuito da un repo diverso rispetto a centos8, ho provato a intervenire su quello che sembra la issue ufficiale sul tema (thanks  @edigiacomo )

https://bugzilla.redhat.com/show_bug.cgi?id=1764934

**Comment by brancomat** [comment]
Ad oggi ancora nessuna risposta, i test di centos8 continuano a fallire (https://simc.arpae.it/moncic-ci/dballe-web/202206070720/master/centos8/build.log) e a cascata pregiudica l'invio automatico a copr (ho lanciato il build per fedora 36 a mano).

C'è da valutare se tentare un build in casa o non distribuire dballe-web per centos/rocky8

**Comment by spanezz** [comment]
Posso cercare di capire quanto si soffre a supportare flask 1.0, o possiamo ragionare di fare bundling di un flask piú nuovo nel pacchetto per centos8/rocky8

**Comment by brancomat** [comment]
Flask ci servirà su centos/rocky8 per altre cose, ho aggiornato i moduli python flask e werkzeug tramite repository simc/stable alle stesse versioni di f34, ora i test passano.
