### ISSUE TITLE
security alert on uglify-js

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/dballe-web#3]
see:
https://github.com/ARPA-SIMC/dballe-web/network/alert/dballe_web/static/Leaflet.markercluster-1.2.0/package.json/uglify-js/open

since `uglify-js` is pinned inside Leaflet maybe the whole Leaflet static libs should be updated?

**Comment by spanezz** [comment]
This has now disappeared once I removed the full markercluster distribution in favour of only the distributed version.

uglify is one of the dependencies used to build markercluster, but we are only using the built version.
