### ISSUE TITLE
build errors on CentOS 7 (invalid syntax )

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/dballe-web#4]
```
Bytecompiling .py files below /root/rpmbuild/BUILDROOT/dballe-web-0.1-1.x86_64/usr/lib/python3.4 using /usr/bin/python3.4
*** Error compiling '/root/rpmbuild/BUILDROOT/dballe-web-0.1-1.x86_64/usr/lib/python3.4/site-packages/dballe_web/session.py'...
  File "/usr/lib/python3.4/site-packages/dballe_web/session.py", line 114
    async def __call__(self):
            ^
SyntaxError: invalid syntax
```
from: https://travis-ci.org/ARPA-SIMC/dballe-web/jobs/499729858

if it isn't a quick fix (e.g. something not supported in python 3.4) maybe we could simply skip builds on CentOS since the web interface for dballe is tipically used outside the production servers on fedora workstations, unless I'm missing something (paging @edigiacomo, @pat1 and @dcesari for advice)

**Comment by edigiacomo** [comment]
`async/await` was introduced in Python 3.5

**Comment by spanezz** [comment]
Does it need to run on centos 7 at all, or can we target mostly workstations, which tend to run on newer OSes? It's a user interface software after all

**Comment by spanezz** [comment]
With quite a number of trial and error exchanges, the current version seems to work on Centos7.

Please open new issues if you see problems that we have missed so far.
